kind: Pod
apiVersion: v1
metadata:
  name: foo-app
  namespace: psa-test-ns
  labels:
    app: foo
spec:
  containers:
  - name: foo-app
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=foo"